[package]
name = "coroutine-rs"
version = "0.0.1"
authors = ["Rustcc Developers"]
license = "MIT/ISC"
repository = "https://github.com/rustcc/coroutine-rs"
description = "Coroutine Library in Rust"
readme = "README.md"
documentation = "https://github.com/rustcc/coroutine-rs/blob/master/README.md"
homepage = "https://github.com/rustcc/coroutine-rs"
build = "build.rs"

[build-dependencies]
gcc = "*"

[lib]
name = "coroutine"
path = "src/lib.rs"

