[package]
name = "coroutine"
version = "0.3.2"
authors = [
    "Y. T. Chung <zonyitoo@gmail.com>",
    "Young.Wu <doomsplayer@gmail.com>",
    "Rustcc Developers"
]
license = "MIT/ISC"
repository = "https://github.com/rustcc/coroutine-rs"
description = "Coroutine Library in Rust"
readme = "README.md"
homepage = "https://github.com/rustcc/coroutine-rs"
keywords = ["coroutine", "green", "thread", "fiber"]

[features]
default = [
    "enable-clonable-handle",
]

enable-clonable-handle = [
    "spin"
]

enable-panic-message = []

[build-dependencies]
gcc = "*"
log = "*"

[lib]
name = "coroutine"
path = "src/lib.rs"

[dependencies]
context = "^0.1.2"

[dependencies.spin]
version = "*"
optional = true

[dev-dependencies]
num_cpus = "*"
